apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: doorman-vaultk8s-job
  namespace: supplycd-ns
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: doorman-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/bevel-vault-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-corda
      namespace: flux-corda
  values:
    metadata:
      name: doorman-vaultk8s-job
      namespace: supplycd-ns
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      role: vault-role
      address: http://vault.dev.aws.blockchaincloudpoc-develop.com:20001
      authpath: cordadoorman
      policy: vault-crypto-supplycd-ns-doorman-ro
      policydata: "{\n    \"policy\": \"path \\\"doorman/data/*\\\" {\n        capabilities = [\\\"read\\\", \\\"list\\\", \\\"create\\\", \\\"update\\\"]\n    }\"\n}"
      secret_path: doorman
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://300125A3D09FFA0A178EC3522C96BBB8.gr7.eu-west-1.eks.amazonaws.com

