dependencies:
  - name: bevel-storageclass
    alias: storage
    repository: "https://sownak.github.io/bevel"
    tags:
      - storage
    version: ~0.15.0
  - name: besu-tessera-node
    alias: tessera
    repository: "file://../besu-tessera-node"
    tags:
      - tessera
    version: ~0.15.0
    condition: tessera.enabled
  - name: besu-tlscert-gen
    alias: tls
    repository: "file://../besu-tlscert-gen"
    tags:
      - bevel
    version: ~0.15.0
    condition: tls.enabled
